version: '3.9'
services:
  python:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./poller:/app
    command: python manage.py runserver 0.0.0.0:8000
